services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq_config/enabled_features:/etc/rabbitmq/enabled_features
    networks:
      - trend-chat

  # Kafka (KRaft single-node for dev)
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=dev-kafka-cluster
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:19092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka/data
    networks:
      - trend-chat

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8989:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - trend-chat

  # Kafka Connect
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "kafka-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_ADVERTISED_PORT: 8083
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONNECT_TOPIC_CREATION_ENABLE: "true"
      CONNECT_TOPIC_CREATION_DEFAULT_REPLICATION_FACTOR: "1"
      CONNECT_TOPIC_CREATION_DEFAULT_PARTITIONS: "1"
      CONNECT_TOPIC_CREATION_DEFAULT_INCLUDE: ".*"
    volumes:
      - ./connect-plugins:/etc/kafka-connect/jars
    depends_on:
      - kafka
      - mysql-user
      - mysql-trend
      - mysql-chat
      - mysql-payment
    networks:
      - trend-chat

  # MySQL - User Service
  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - trend-chat

  # MySQL - Trend Service
  mysql-trend:
    image: mysql:8.0
    container_name: mysql-trend
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: trend_service
      MYSQL_USER: trend
      MYSQL_PASSWORD: trend1234
    volumes:
      - mysql-trend-data:/var/lib/mysql
    networks:
      - trend-chat

  # MySQL - Chat Service
  mysql-chat:
    image: mysql:8.0
    container_name: mysql-chat
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: chat_service
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat1234
    volumes:
      - mysql-chat-data:/var/lib/mysql
    networks:
      - trend-chat

  # MySQL - Payment Service
  mysql-payment:
    image: mysql:8.0
    container_name: mysql-payment
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: payment_service
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment1234
    volumes:
      - mysql-payment-data:/var/lib/mysql
    networks:
      - trend-chat

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - trend-chat

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - trend-chat

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    restart: always
    networks:
      - trend-chat

volumes:
  rabbitmq-data:
  kafka_data:
  mysql-user-data:
  mysql-trend-data:
  mysql-chat-data:
  mysql-payment-data:
  prometheus-data:
  grafana-storage:

networks:
  trend-chat:
    driver: bridge
